apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
        - name: game-service
          image: troshan96/game-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: game-db
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: admin123
            - name: DB_NAME
              value: gamesdb
            - name: DB_PORT
              value: "3306"