apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: games-db-pvc
spec:
  storageClassName: my-go2-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-db
  template:
    metadata:
      labels:
        app: game-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin123"
            - name: MYSQL_DATABASE
              value: "gamesdb"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: games-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: game-db
spec:
  selector:
    app: game-db
  ports:
    - port: 3306
      targetPort: 3306