apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: NodePort
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
